version: "3"
services: 
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes: 
      - ./docker/data/:/data/db/
    ports: 
      - '27017:27017'
  api:
    container_name: api-container
    build: .
    image: clean-node-api
    restart: always
    command: npm run debug
    volumes: 
      - ./package.json:/usr/src/clean-node-api/package.json
      - ./dist/:/usr/src/clean-node-api/dist/
    ports: 
      - '5050:5050'
      - '9222:9222'
    links: 
     - mongo

networks:
  default:
    driver: "bridge"
    
