version: "3"
services: 
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes: 
      - db-data:/data/db/
    ports: 
      - '27019:27017'
    networks:
      api-network: 
        ipv4_address: 192.168.10.2
  api:
    container_name: api-container
    build: .
    image: clean-node-api
    working_dir: /usr/src/clean-node-api
    entrypoint: npm rum debug
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
      - API_HOST=api
      - PORT=5000
    volumes: 
      - ./dist/:/usr/src/clean-node-api/dist/
    ports: 
      - '5000:5000'
      - '9222:9222'
    depends_on:
      - mongo
    networks:
      api-network: 
        ipv4_address: 192.168.10.3

networks:
  api-network:
    ipam:
      config:
        - subnet: 192.168.10.0/24
    
volumes:
  db-data:
